
    erDiagram
    SolucionLimpieza ||--o{ TipoMancha : solucion_tipos_mancha
    SolucionLimpieza ||--o{ Material : solucion_materiales
    SolucionLimpieza ||--o{ Ingrediente : solucion_ingredientes
    Ingrediente ||--o{ Ingrediente : ingredientes_incompatibles
    Usuario ||--o{ SolucionFavorita : guarda
    SolucionLimpieza ||--o{ SolucionFavorita : es guardada
    Categoria ||--o{ TipoMancha : categoriza
    TipoMancha ||--o{ SolucionLimpieza : "tiene"
    SolucionLimpieza ||--o{ Ingrediente : "contiene"
    SolucionLimpieza ||--o{ Material : "aplica a"
    UsuarioBase ||--o{ SolucionFavorita : "guarda"
    SolucionLimpieza ||--o{ SolucionFavorita : "es guardada"
    Categoria ||--o{ TipoMancha : "categoriza"
    Cliente ||--o{ Pedido : "realiza"

    %%  una sustancia puede ser mancha e ingrediente o ser macha de una solución %%
    TipoMancha ||--o{ TipoMancha : "manchas secundarias"
    TipoMancha ||--o{ Ingrediente : "puede ser mancha" "0..1"
